---
- name: Prep Nodes for Technitium DNS Cluster
  hosts: dns_nodes
  become: true
  tasks:
    # create a dedicated user to run Technitium in rootless podman
    - name: Create dnsuser with lingering
      ansible.builtin.user:
        name: "{{ dns_user }}"
        shell: /sbin/nologin
        system: true
        create_home: true
        uid: "{{ dns_user_uid }}"

    - name: Check if subuid range is already assigned
      ansible.builtin.shell: "grep -q '^{{ dns_user }}:' /etc/subuid"
      register: subid_check
      failed_when: false
      changed_when: false

    - name: Set subordinate ranges (100000-165535)
      ansible.builtin.command: "{{ item }}"
      when: subid_check.rc != 0
      loop:
        - "usermod --add-subuids 100000-165535 {{ dns_user }}"
        - "usermod --add-subgids 100000-165535 {{ dns_user }}"

    # enable lingering for the user to allow running containers without an active session
    - name: Enable lingering for dnsuser
      ansible.builtin.command: "loginctl enable-linger {{ dns_user }}"
      args:
        creates: "/var/lib/systemd/linger/{{ dns_user }}"

    # ensure firewalld is installed
    - name: Ensure firewalld is installed and running
      ansible.builtin.dnf:
        name: firewalld
        state: installed

    # ensure firewalld is running
    - name: Ensure firewalld is running and enabled
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true

    # free up port 53 by disabling the systemd-resolved stub
    - name: Disable systemd-resolved stub listener
      ansible.builtin.blockinfile:
        path: /etc/systemd/resolved.conf
        create: true
        block: |
          [Resolve]
          DNSStubListener=no
        owner: root
        group: root
        mode: '0640'

    # restart systemd-resolved to apply the configuration change
    - name: Restart systemd-resolved to apply changes
      ansible.builtin.systemd:
        name: systemd-resolved
        state: restarted

    # redirect privileged low port 53 traffic to unprivileged contianer high port 5053 using firewalld
    - name: Configure Firewalld redirects (Port 53 to 5053)
      ansible.posix.firewalld:
        rich_rule: 'rule family="ipv4" forward-port port="53" protocol="{{ item }}" to-port="5053"'
        state: enabled
        permanent: true
        immediate: true
      loop: [udp, tcp]

    # the same for the loopback iterface to test queries locally on the node
    - name: Add local loopback redirect (Direct Rule)
      ansible.builtin.shell: |
        firewall-cmd --permanent --direct --add-rule ipv4 nat OUTPUT 0 -p {{ item }} -o lo --dport 53 -j REDIRECT --to-ports 5053
      loop: [udp, tcp]
      changed_when: false

    # open the ports needed to allow dns and management traffic to the node
    - name: Open management and cluster ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      loop: ["5053/udp", "5053/tcp", "5380/tcp", "53443/tcp"]