[defaults]
host_key_checking=True

[all:vars]
ansible_user=<changeme>
vip_address=<vip of DNS cluster
dns_user=<dedicated user for running Technitium>
dns_user_uid=<dedicated user UID for running Technitium>

[dns_nodes]
node1 ansible_host=<node1 ip> vrrp_priority=100 vrrp_state=MASTER
node2 ansible_host=<node2 ip> vrrp_priority=90  vrrp_state=BACKUP
node3 ansible_host=<node3 ip> vrrp_priority=80  vrrp_state=BACKUP

